# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - amarumed-frontend-webapp

on:
  push:
    branches:
      - front
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://amarumedcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9d2f08f3dfb4396b648a2ab514871e9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b2aada756e8843e7ade06d48477d2708 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: amarumedcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9d2f08f3dfb4396b648a2ab514871e9 }}/frontamarumed:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'amarumed-frontend-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_419e9931a4974f4cbaf4d7b72f5abe0b }}
        images: 'amarumedcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9d2f08f3dfb4396b648a2ab514871e9 }}/frontamarumed:${{ github.sha }}'